CREATE DATABASE employ;
USE employ;
CREATE TABLE employee(Eid int(10) PRIMARY KEY NOT NULL,Ename VARCHAR(20) NOT NULL,Age INT NOT NULL,Salary INT NOT NULL);
INSERT INTO employee (Eid, Ename, Age,Salary) VALUES(101, 'ANU', 22,9000);
INSERT INTO employee (Eid, Ename, Age,Salary) VALUES(102, 'SHANE', 29,8000);
INSERT INTO employee (Eid, Ename, Age,Salary) VALUES(103, 'ROHAN', 34,6000);
INSERT INTO employee (Eid, Ename, Age,Salary) VALUES(104, 'SCOTT', 44,10000);
INSERT INTO employee (Eid, Ename, Age,Salary) VALUES(105, 'TIGER', 35,8000);
INSERT INTO employee (Eid, Ename, Age,Salary) VALUES(106, 'ALEX', 27,7000);
INSERT INTO employee (Eid, Ename, Age,Salary) VALUES(107, 'ABHI', 29,8000);
SELECT * FROM employee;
SELECT COUNT(Ename)FROM employee;
SELECT MAX(Age)FROM employee;
SELECT MIN(Age)FROM employee;
SELECT SUM(Age)FROM employee;
SELECT AVG(Age)FROM employee;
CREATE VIEW employe AS SELECT Age FROM employee;
SELECT * FROM employe;
SELECT Salary FROM employee GROUP BY Salary;
SELECT  DISTINCT Salary  FROM employee ORDER BY Salary ASC;
SELECT DISTINCT Salary  FROM employee ORDER BY Salary DESC;